### ISSUE TITLE
Kismet GUI is not working

### ISSUE THREAD

**Issue by MaciejStawiar** [WLAN-Pi/wlanpi#1]
Hi Guys,
Wanted to test Kismet in new release and found that it is not working properly.
Starting from CLI works fine and prints those info messages like INFO: Detected new 802.11 Wi-Fi device D4:6A:6A:C2:26:C0
but when I go to the server web page, it shows this initial dialog to provide user and password, then when I put the data and Save nothing is showing - blank page with Kismet logo and empty drop-down menu, no content. When I refresh the page it shows again initial dialog with user and password. As I remember in previous version I had to provide correct login credentials for the server - maybe this is not working?
Thanks for Your job!

**Comment by djjerdog** [comment]
I'm unable to duplicate, which browser are you using? Could you try a different browser or using an incognito tab?

**Comment by djjerdog** [comment]
Also, in 1.8 the user credentials (username / password) are not set automatically and need to be set the first time you launch Kismet

**Comment by MaciejStawiar** [comment]
I tested it on 2 computers and 3 browsers (Chrome, Edge, Maxthon) but both computers are running latest BitDefender. Now I tried to get there on my mobile and it is working :) So looks like firewall issue.

**Comment by djjerdog** [comment]
Bah, ok, good to know, thank you for that info. Glad to hear you at least narrowed down what the culprit is. Is it a specific port that is being blocked?
