### ISSUE TITLE
Wrong broadcast-address in dhcpd.conf

### ISSUE THREAD

**Issue by yananet** [WLAN-Pi/wlanpi#17]
Hello,
please correct me if this issue should be reported in different place.
 
Looks that `option broadcast-address` is set to `192.168.42.1` in `dhcpd.conf`
```
wlanpi@wlanpi:~$ tail /etc/dhcp/dhcpd.conf
# WLAN Pi DHCP Server config
subnet 192.168.42.0 netmask 255.255.255.224 {
  range 192.168.42.2 192.168.42.30;
#  option domain-name-servers ns1.internal.example.org;
#  option domain-name "internal.example.org";
#  option routers 192.168.42.1;
  option broadcast-address 192.168.42.1;
  default-lease-time 600;
  max-lease-time 7200;
}
wlanpi@wlanpi:~$ 
```
Thus my desktop is getting wrong broadcast address via USB OTG
```
16: enp0s26u1u3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether be:b8:06:ea:b2:15 brd ff:ff:ff:ff:ff:ff
    inet 192.168.42.6/27 brd 192.168.42.1 scope global deprecated dynamic noprefixroute enp0s26u1u3
       valid_lft 49sec preferred_lft 0sec
    inet6 fe80::bcb8:6ff:feea:b215/64 scope link 
       valid_lft forever preferred_lft forever
```
```
[yananet@arch-desktop]: ~>$ ping 192.168.42.1
ping: Do you want to ping broadcast? Then -b. If not, check your local firewall rules
[yananet@arch-desktop]: ~>$ 
```
I had to disable DHCP to access 192.168.42.1.
and now it is working if I changed the broadcast address with correct broadcast address.
```
wlanpi@wlanpi:~$ tail /etc/dhcp/dhcpd.conf
# WLAN Pi DHCP Server config
subnet 192.168.42.0 netmask 255.255.255.224 {
  range 192.168.42.2 192.168.42.30;
#  option domain-name-servers ns1.internal.example.org;
#  option domain-name "internal.example.org";
#  option routers 192.168.42.1;
  option broadcast-address 192.168.42.31;
  default-lease-time 600;
  max-lease-time 7200;
}
wlanpi@wlanpi:~$ 
```
correct me if I am wrong or let me know if this is expected.

Tested version : **WLAN Pi 1.9.1 [WLPC edition]**

Thanks.

**Comment by wifinigel** [comment]
yananet,

Thanks for the report. This has fixed an issue I have been seeing for a long time and could not track down! Thanks for taking the time to report this, it's going to make a difference to lots of users accessing their WLAN Pi via the local USB/OTG connection.

I've added the updated file to our misc-files repo so that we don't have this issue in future builds.

Thanks again.

Nigel.
