### ISSUE TITLE
Implement additional driver Netgear A6210

### ISSUE THREAD

**Issue by patoberli** [WLAN-Pi/wlanpi#3]
Hi
It would be great if you could implement, as beta marked maybe, the following driver for the Netgear A6210. I've compiled and used it in my installation (via DKMS), running build 1.8.3 successfully.
Driver source: https://github.com/kaduke/Netgear-A6210
It would then support all wi-fi adapters based on: 
Ralink / Mediatek mt766u, mt7632u and mt7612u chipsets.
In particular, the driver supports several USB dongles such as Netgear-A6210, ASUS USB-AC55, ASUS USB-N53 and EDUP EP-AC1601.

Thanks for considering.

**Comment by avgerinosf** [comment]
Hi, 
While waiting for the upcoming release and perhaps future support of this driver, could you please share the DKMS method ? 
Thanks

**Comment by ZeroChaos-** [comment]
This is supported via in kernel driver from 4.19

**Comment by patoberli** [comment]
Hi, sorry for the late reply, was on holiday.
Regarding the DKMS question, it's written in the README on the GIT page, here is the important part:
On Debian-based distros, you can add the module to DKMS so it will automatically build and install on each successive kernel upgrade. To do this, issue the following commands from within the repo's folder:
$ cd ..
$ sudo mv Netgear-A6210/ /usr/src/netgear-a6210-2.5.0
$ sudo dkms install netgear-a6210/2.5.0

**Comment by jolla** [comment]
MediaTek MT76 drivers were added to WLAN Pi v1.9
