### ISSUE TITLE
cannot boot v2.1.3 on neo2

### ISSUE THREAD

**Issue by konikofi** [WLAN-Pi/wlanpi#42]
flashed wlanpi-neo-v2.1.3-231111.img.gz using balena-etcher
inserted sd card into neo2 device and waited 5 min
- ethernet port shows activity, but there is no on-screen display

same process to flash wlanpi-neo2-v2.1.0-230410.img.gz which works fine on same neo2 device

**Comment by joshschmelzle** [comment]
It looks like you used `wlanpi-neo-v2.1.3-231111.img.gz` when you should have used `wlanpi-neo2-v2.1.3-231111.img.gz`. That is the neo2 image rather than the neo image.

**Comment by konikofi** [comment]
that was it, sorry for the noise!

**Comment by joshschmelzle** [comment]
All good! Thanks for confirming you got it sorted out.
