### ISSUE TITLE
WLAN Pi Hotspot testing

### ISSUE THREAD

**Issue by wifinigel** [WLAN-Pi/wlanpi#7]
The hotspot code has been updated to reflect the enhancement from Francois which allows connectivity between interfaces so that anyone connected to the SSID can route traffic out through the ethernet port.

This has been posted in the repo but needs testing further to make sure there are no unintended side-effects when switching in and out of hotspot mode on other WLANPi functions/utilities.

**Comment by jiribrejcha** [comment]
Done. Please close.
